### ISSUE TITLE
UI.Modal dosen't shown both on touchstonejs & touchstone-starter

### ISSUE THREAD

**Issue by Duan112358** [touchstonejs/touchstonejs#63]
I copy the code & spinner logic from [home.js](https://github.com/Thinkmill/touchstone-starter/blob/master/src/js/views/home.js), but nothing happened when calling show spinner function.

While, on DOM , only a `<noscript data-reactid="xxxxxx' ....></noscript>` was rendered when toggling the spinner.

same thing happened on touchstone-starter demo.

**Comment by 007lva** [comment]
+1

**Comment by jossmac** [comment]
Hi @Duan112358 

Sorry to hear you had a bad experience with that. Since raising this issue touchstone has mature quite a lot.

Would you mind trying the latest version [0.4.2](https://www.npmjs.com/package/touchstonejs) using [UI.Popup](https://github.com/touchstonejs/touchstonejs/blob/master/src/ui/Popup.js) and [UI.PopupIcon](https://github.com/touchstonejs/touchstonejs/blob/master/src/ui/PopupIcon.js)

Please let us know how you go

**Comment by jossmac** [comment]
@Duan112358 any luck with this?

**Comment by jossmac** [comment]
Cannot reproduce
