### ISSUE TITLE
Toggle Styling on Windows Phone

### ISSUE THREAD

**Issue by rickyvetter** [touchstonejs/touchstonejs#7]
The toggle gets scrunched up on WP instead of filling the full width of the screen.
![wp_ss_20141211_0001](https://cloud.githubusercontent.com/assets/4370652/5396696/36e334aa-8122-11e4-847c-1b6a90d679d3.jpg)

**Comment by Johnius** [comment]
@JedWatson you can use Browserstack now! It supports WP 8.1

**Comment by wmaurer** [comment]
i looked into this, but can't make a PR, because I can't find the source for demo.touchstone.io. This repository serves the touchstone-starter, and the problem does not exist with the touchstone-starter.

Anyway the fix is simple. On demo.touchstone.js, the toggle-item class has display:table-cell. Changing it to display:block fixes the problem.

I also can't find toggle-item in the repostory, I assume demo.touchstone.io is based on an old version of touchstone? If so the issue can probably be closed.

**Comment by jossmac** [comment]
@wmaurer @rickyvetter @Johnius Touchstone has changed significantly since this issue was raised. For a current demo you can [visit the starter app](https://touchstonejs.github.io/touchstonejs-starter)

I doubt that the problem remains, so i'm closing the issue. Will reopen if evidence to the contrary is provided
